#!/usr/bin/env python3
"""Run both studies and emit Markdown + CSV reports under ./outputs/.

Usage:
    python analyze.py                 # threshold >= 3 (default)
    python analyze.py --threshold 4   # stricter relevance
    python analyze.py --stdout        # also print tables to the terminal
"""
from __future__ import annotations

import argparse
import csv
import os
from typing import Dict, List

from studies import newest, pilot

OUT_DIR = os.path.join(os.path.dirname(__file__), "outputs")

PILOT_COLS = ["nDCG@5", "nDCG@10", "P@5", "P@10", "MRR", "FHR", "Unr@5", "Unr@10"]
NEW_COLS = ["N", "nDCG@5", "nDCG@10", "P@5", "P@10", "MRR", "FHR", "hit_rate", "avgRating"]


def _fmt(v) -> str:
    if v is None:
        return "-"
    if isinstance(v, float):
        return f"{v:.4f}"
    return str(v)


def _md_table(header: List[str], rows: List[List[str]]) -> str:
    line = "| " + " | ".join(header) + " |"
    sep = "| " + " | ".join("---" for _ in header) + " |"
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return f"{line}\n{sep}\n{body}\n"


def _system_rows(results: Dict[str, dict], cols: List[str], label_extra: bool = False) -> List[List[str]]:
    out = []
    for system, m in results.items():
        cells = [system] + [_fmt(m.get(c)) for c in cols]
        if label_extra and m.get("source") == "frozen":
            cells[0] = system + " *"
        out.append(cells)
    return out


def build_report(threshold: int) -> str:
    md: List[str] = []
    md.append(f"# Maestro search-study results (relevance threshold ≥ {threshold})\n")
    md.append("_Generated by `analyze.py`. Metrics are the shared definitions in "
              "`studies/metrics.py` (identical to archRag/eval)._\n")

    # ---- Pilot ----
    p = pilot.evaluate(threshold)
    md.append("## Pilot study — Apache HDFS (8 systems)\n")
    md.append("Recall-style evaluation against pooled 23-student ground truth. "
              "Rows marked `*` are frozen from the live-service run "
              "(PyLucene variants); all others are recomputed from raw.\n")
    md.append(_md_table(["System"] + PILOT_COLS, _system_rows(p, PILOT_COLS, label_extra=True)))

    # ---- Newest overall ----
    n = newest.evaluate(threshold)
    md.append("\n## Newest study — 5 Apache projects (3 systems)\n")
    md.append("Within-list ranking quality (each student rated that engine's own "
              "results). Unr@k is omitted — 0 by construction.\n")
    md.append(_md_table(["System"] + NEW_COLS, _system_rows(n, NEW_COLS)))

    # ---- Per project ----
    md.append("\n### Per-project breakdown\n")
    for proj, res in newest.evaluate_by_project(threshold).items():
        md.append(f"\n**{proj}**\n")
        md.append(_md_table(["System"] + NEW_COLS, _system_rows(res, NEW_COLS)))

    # ---- Per question type ----
    md.append("\n### Per-question-type breakdown\n")
    for q, res in newest.evaluate_by_question(threshold).items():
        md.append(f"\n**{q}**\n")
        md.append(_md_table(["System"] + NEW_COLS, _system_rows(res, NEW_COLS)))

    return "\n".join(md)


def write_csvs(threshold: int) -> None:
    # Pilot
    with open(os.path.join(OUT_DIR, "pilot_hdfs.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["system", "source"] + PILOT_COLS)
        for s, m in pilot.evaluate(threshold).items():
            w.writerow([s, m.get("source", "")] + [m.get(c) for c in PILOT_COLS])

    # Newest — overall + breakdowns in one long/tidy file
    with open(os.path.join(OUT_DIR, "newest_5projects.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["scope", "group", "system"] + NEW_COLS)
        for s, m in newest.evaluate(threshold).items():
            w.writerow(["overall", "all", s] + [m.get(c) for c in NEW_COLS])
        for proj, res in newest.evaluate_by_project(threshold).items():
            for s, m in res.items():
                w.writerow(["project", proj, s] + [m.get(c) for c in NEW_COLS])
        for q, res in newest.evaluate_by_question(threshold).items():
            for s, m in res.items():
                w.writerow(["question", q, s] + [m.get(c) for c in NEW_COLS])


def main() -> None:
    ap = argparse.ArgumentParser(description="Analyze Maestro search studies")
    ap.add_argument("--threshold", type=int, default=3, help="Relevance threshold (rating >= threshold)")
    ap.add_argument("--stdout", action="store_true", help="Also print the report to stdout")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    report = build_report(args.threshold)
    md_path = os.path.join(OUT_DIR, f"report_threshold{args.threshold}.md")
    with open(md_path, "w") as f:
        f.write(report)
    write_csvs(args.threshold)

    print(f"Wrote {md_path}")
    print(f"Wrote {os.path.join(OUT_DIR, 'pilot_hdfs.csv')}")
    print(f"Wrote {os.path.join(OUT_DIR, 'newest_5projects.csv')}")
    if args.stdout:
        print("\n" + report)


if __name__ == "__main__":
    main()
